language: android
jdk: oraclejdk8
sudo: false

android:
  components:
    - tools
    - build-tools-29.0.2
    - android-29
    - extra-android-support
    - extra-android-m2repository
    - extra-google-m2repository

script:
  - ./gradlew -p library test --console=plain
